os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - RUSTFLAGS='-C target-feature=+crt-static'
  - RUSTFLAGS='-C target-feature=-crt-static'
  - RUSTFLAGS='-Clinker-plugin-lto -Clinker=clang-8 -Clink-arg=-fuse-ld=lld-8'

script:
  - cargo test --all
  - cargo test --all --release
  
