os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - RUSTFLAGS='-C target-feature=+crt-static'
  - RUSTFLAGS='-C target-feature=-crt-static'
  - MUSL=true

script:
  - ./test.sh

matrix:
  exclude:
    - os: osx
      env: MUSL=true
    - os: windows
      env: MUSL=true
