[workspace]
resolver = "2"
members = [ 
    "ctor", 
    "dtor", 
    "macro-magic",
    "linktime",
    "linktime-proc-macro",
    "link-section",
    "scattered-collect",
    "tests"
]
default-members = [
    "ctor",
    "dtor",
    "linktime",
    "macro-magic",
    "link-section",
    "scattered-collect",
    "tests"
]
exclude = []

[workspace.package]
authors = ["Matt Mastracci <matthew@mastracci.com>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/linktime"

[workspace.dependencies]
ctor = { path = "ctor", version = "1.0.13", default-features = false }
dtor = { path = "dtor", version = "1.0.6", default-features = false }
link-section = { path = "link-section", version = "0.19.3", default-features = false }
linktime = { path = "linktime", version = "0.19.0", default-features = false }
scattered-collect = { path = "scattered-collect", version = "0.22.2" }

linktime-proc-macro = { path = "linktime-proc-macro", version = "0.2.3" }
