name: CodSpeed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6
        with:
          toolchain: stable
          cache: false

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Cache Rust files
        continue-on-error: true # https://github.com/actions/cache/issues/1754
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/**/*.rlib
          key: codspeed-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            codspeed-${{ runner.os }}-cargo-

      - name: Build the benchmark targets
        run: cargo codspeed build --package scattered-collect

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: cargo codspeed run --package scattered-collect
