name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - id: generate
        uses: "mmastrac/mmm-matrix@v1"
        with:
          input: |
            project: [ctor]
            needs:
              $match:
                "this.job == 'wasm'": "wasmtime-cli"
                "this.job == 'test'": "cargo-expand"
            rust-toolchain:
              $match:
                "this.job == 'miri'": nightly
                "this.job == 'clippy'": nightly
                "this.job == 'build'": [stable, beta, nightly]
                "this.job == 'build-minimal'": ["1.65"]
                "true": "stable"
            rust-extra-target:
              $match:
                "this.job == 'wasm'": "wasm32-unknown-unknown,wasm32-wasip1"
            rust-components:
              $match:
                "this.job == 'miri'": "miri,rust-src"
                "this.job == 'clippy'": "clippy"
            label:
              linux:
                os: ubuntu-latest
                job: [build, build-minimal, clippy, test, miri, wasm]
              macos:
                os: macOS-latest
                job: [clippy, test, miri]
              windows:
                os: windows-latest
                job: [clippy, test]
          config: |
            github: ${{ toJSON(github) }}

  build:
    name: ${{ matrix.label }} / ${{ matrix.job }} (${{ matrix.rust-toolchain }})
    runs-on: ${{ matrix.os }}
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      CACHE_KEY: 1
      CLIPPY_LINTS: >-
        -D clippy::all
        -D deprecated-safe
        -D future-incompatible
        -D keyword-idents
        -D let-underscore
        -D nonstandard-style
        -D refining-impl-trait
        -D rust-2018-compatibility
        -D rust-2018-idioms
        -D rust-2021-compatibility
        -D rust-2024-compatibility
        -D unused
        -D unsafe_code
        -D unreachable-pub
        -D missing-docs

    steps:
    - uses: actions/checkout@v6

    - name: Install required Rust tools
      uses: taiki-e/install-action@v2
      if: ${{ matrix.needs }}
      with:
        tool: ${{ matrix.needs }}
  
    - name: Install Rust toolchain (${{ matrix.rust-toolchain }})
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: ${{ matrix.rust-components }}
        target: ${{ matrix.rust-extra-target }}

    - name: Cache Rust files
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/**/*.rlib
        key: ${{ env.CACHE_KEY }}-${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ env.CACHE_KEY }}-${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}-

    - name: Run ${{ matrix.job }}
      shell: bash
      run: ".github/jobs/${{ matrix.job }}.sh"
