name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - id: generate
        uses: "mmastrac/mmm-matrix@v1"
        with:
          input: |
            project: [ctor, link-section]
            needs:
              $match:
                "this.job == 'wasm'": "wasmtime-cli"
                "this.job == 'test'": "cargo-expand"
            rust-toolchain:
              $match:
                "this.job == 'miri'": "nightly"
                "this.job == 'clippy'": "nightly"
                "true": "stable"
            rust-components:
              $match:
                "this.job == 'miri'": "miri"
                "this.job == 'clippy'": "clippy"
            label:
              linux:
                os: ubuntu-latest
                job: [build, clippy, test, miri, wasm]
              macos:
                os: macOS-latest
                job: [build, clippy, test, miri]
              windows:
                os: windows-2019
                job: [build, clippy, test, miri]
          config: |
            github: ${{ toJSON(github) }}

  build:
    name: ${{ matrix.label }} / ${{ matrix.job }} (${{ matrix.rust-toolchain }})
    runs-on: ${{ matrix.os }}
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      CACHE_KEY: 1
      CLIPPY_LINTS: >-
        -D clippy::all
        -D deprecated-safe
        -D future-incompatible
        -D keyword-idents
        -D let-underscore
        -D nonstandard-style
        -D refining-impl-trait
        -D rust-2018-compatibility
        -D rust-2018-idioms
        -D rust-2021-compatibility
        -D rust-2024-compatibility
        -D unused
        -D unsafe_code
        -D unreachable-pub
        -D missing-docs

    steps:
    - uses: actions/checkout@v3

    - name: Install required crates
      uses: taiki-e/install-action@v2
      with:
        tool: ${{ needs.generate-matrix.outputs.matrix.tool }}
  
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ needs.generate-matrix.outputs.matrix.toolchain }}
        components: clippy,rustfmt,miri

    - name: Cache Rust files
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/wasm32-unknown-unknown
        key: ${{ runner.os }}-cargo-${{ env.CACHE_KEY }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ env.CACHE_KEY }}-

    - name: Run job
      run: bash "$GITHUB_WORKSPACE/.github/jobs/${{ matrix.job }}.sh"
